services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: emanuele
      POSTGRES_PASSWORD: emanuele
      POSTGRES_DB: tabletop_companion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emanuele -d tabletop_companion"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://emanuele:emanuele@db:5432/tabletop_companion
      NODE_ENV: development
      PORT: 3001
      CORS_ORIGIN: http://localhost:8080
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local 